export const RECEIVE_ME = 'RECEIVE_ME'
export const RECEIVE_PEOPLE_SUCCESS = 'RECEIVE_PEOPLE_SUCCESS'
export const RECEIVE_PEOPLE_FAILURE = 'RECEIVE_PEOPLE_FAILURE'
export const UPDATE_EMAIL_CHARS = 'UPDATE_EMAIL_CHARS'